
--insert into EMPLOYEE (ID,NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values (6,'Stella Wagner','StWagner@rand.com','032445623','1997-03-21',1245130);

--ALTER TABLE Users ADD UserID INT NOT NULL PRIMARY KEY IDENTITY(1,1)

--Insert into DOCUMENTATION (ID,PROJECT_NAME,LENGTH,LANGUAGE) values (8,'School program',80,'php');

--select * from DOCUMENTATION;
--Insert into TASK (ID,TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values (11,'Hierarchy Maintenance','Look over hierarchy levels',1,'2023-05-20', 5);
--SELECT * FROM TASK;

--SELECT * FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30';

--SELECT * FROM EMPLOYEE WHERE ID = (SELECT ID FROM (SELECT ASSIGNEE, 

--
--BIRAMO RADNIKE KOJI SU IMALI TASKOVE ZA MAJ
--SELECT ASSIGNEE FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30';

--GRUPISEMO DA VIDIMO KOJI SU
--SELECT ASSIGNEE FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30' GROUP BY ASSIGNEE;

--SELECT * FROM EMPLOYEE WHERE ID IN (SELECT ASSIGNEE FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30' GROUP BY ASSIGNEE);

--SELECT TOP 3 * FROM EMPLOYEE ORDER BY MONTHLY_SALARY DESC;

--select * from task;
--select TOP 2 * from EMPLOYEE WHERE ID IN ( SELECT ASSIGNEE FROM TASK ORDER BY ASSIGNEE DESC

 --SELECT ASSIGNEE FROM TASK ORDER BY (  ) DESC;

 --SELECT ASSIGNEE,COUNT(ID) FROM TASK GROUP BY ASSIGNEE  ORDER BY COUNT(ID) DESC;

-- SELECT ASSIGNEE,COUNT(ID) FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30' GROUP BY ASSIGNEE  ORDER BY COUNT(ID) DESC;


-- SELECT * FROM TASK;

 --SELECT * FROM EMPLOYEE WHERE ID IN ( SELECT TOP 2 ASSIGNEE FROM TASK WHERE DUE_DATE BETWEEN '2023-05-01' AND '2023-05-30' GROUP BY ASSIGNEE  ORDER BY COUNT(ID) DESC);


 --CREATE TABLE Person (
  --  Personid int IDENTITY(1,1) PRIMARY KEY,
  --  LastName varchar(255) NOT NULL,
  --  FirstName varchar(255),
  --  Age int--
---);@@@@

--DROP TABLE TASK;
--DROP TABLE EMPLOYEE;

--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Layne Mata','LayneMata@yahoo.com','021445623','1992-05-11',120030);
--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Ravi Kumar','RaviKumar@dummy.com','038126261','1993-11-08',1012291);
--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Ivan Torento','IvanTorento@gmail.com','025945623','1998-05-28',103030);
--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Steven Lyn','StevenLyn@rand.com','098745623','1994-07-16',131030);
--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Maya Muller','MayaMuller@rand.com','032445623','1997-03-21',120130);


--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Kai Tommas','KaiTomas@rand.com','05512345','1992-09-26',141030);
--Insert into EMPLOYEE (NAME,EMAIL,PHONE_NUMBER,DATE_OF_BIRTH,MONTHLY_SALARY) values ('Teo Wagner','TeoWagner@blabla.com','066445623','1995-08-13',252130);


--CREATE TABLE [dbo].[DOCUMENTATION] (
--    [ID]           INT         IDENTITY (1, 1) NOT NULL,
--    [PROJECT_NAME] VARCHAR (255) NOT NULL,
--    [LENGTH]       INT           NULL,
--    [LANGUAGE]     VARCHAR (50)  NULL,
--    PRIMARY KEY CLUSTERED ([ID] ASC)
--);

--Insert into DOCUMENTATION (PROJECT_NAME,LENGTH,LANGUAGE) values ('Book Store',20,'c#');
--Insert into DOCUMENTATION (PROJECT_NAME,LENGTH,LANGUAGE) values ('Swimming Pool App',40,'java');
--Insert into DOCUMENTATION (PROJECT_NAME,LENGTH,LANGUAGE) values ('Delivery App',24,'php');
--Insert into DOCUMENTATION (PROJECT_NAME,LENGTH,LANGUAGE) values ('School program',80,'php');


--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Management meeting','Mnagement meeting with the team',7, '2023-04-29', 3);
--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Writing emails','Writing emails',7,'2023-04-30', 4);
--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Code organisation','Organizing the code',8, '2023-04-01', 1);
--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Handling problem situations','Fixing problem situations amonst employees',3, '2023-04-05', 2);
--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Workplace improvement','Setting up the workplace',1, '2023-04-11', 3);

--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Architecture design','Setting up the architecture of the project',3,'2023-05-20', 10);

--Insert into TASK (TITLE,DESCRIPTION,ASSIGNEE, DUE_DATE, DOCUMENTATION_NUMBER) values ('Hierarchy Maintenance','Look over hierarchy levels',1,'2023-04-30', 3);

--SELECT * FROM DOCUMENTATION WHERE ID = (SELECT MAX(

--SELECT MAX (mycount) 
--FROM (SELECT DOCUMENTATION_NUMBER,COUNT(DOCUMENTATION_NUMBER) mycount 
--FROM TASK 
--GROUP BY DOCUMENTATION_NUMBER)

--	SELECT DOCUMENTATION_NUMBER, COUNT(DOCUMENTATION_NUMBER) AS NUMBER_OF_TASKS FROM TASK GROUP BY DOCUMENTATION_NUMBER;

--	SELECT DOCUMENTATION_NUMBER, COUNT(DOCUMENTATION_NUMBER) AS NUMBER_OF_TASKS FROM TASK GROUP BY DOCUMENTATION_NUMBER ORDER BY COUNT(DOCUMENTATION_NUMBER) DESC;

--	SELECT DOCUMENTATION_NUMBER FROM TASK GROUP BY DOCUMENTATION_NUMBER ORDER BY COUNT(DOCUMENTATION_NUMBER) DESC;

--	SELECT TOP 1 DOCUMENTATION_NUMBER FROM TASK GROUP BY DOCUMENTATION_NUMBER ORDER BY COUNT(DOCUMENTATION_NUMBER) DESC;

--SELECT * FROM DOCUMENTATION WHERE ID = (SELECT TOP 1 DOCUMENTATION_NUMBER FROM TASK GROUP BY DOCUMENTATION_NUMBER ORDER BY COUNT(DOCUMENTATION_NUMBER) DESC);

--select * FROM TASK WHERE DOCUMENTATION_NUMBER = 2;
